version: "3"
services: 
  xlsxltest2:
    build:
      context: .
      dockerfile: Dockerfile2
    volumes:
      - .:/usr/app
    environment:
      - PYTHON_VERSION=2
  xlsxltest3:
    build:
      context: .
      dockerfile: Dockerfile3
    volumes:
      - .:/usr/app      
    environment:
      - PYTHON_VERSION=3
